# There are two kinds of continuous integration jobs in this project:
#
# - Every code submission or master push passes continuous integration on the
#   minimal supported Rust version and the current stable Rust version.
# - Two times a month, a scheduled job makes sure that the code remains
#   compatible and lint-free on upcoming Rust toolchains (beta and nightly).
#
# No caching of Rust toolchains or target directories is performed on unstable
# runs, since those runs are rare and the caches would be invalidated inbetween
# two of them (especially for nightly toolchains).

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 2,16 * *'

name: Continuous Integration

env:
  RUSTFLAGS: -D warnings
  MINIMAL_RUST: 1.70.0  # Minimal Supported Rust Version
  CARGO_NET_GIT_FETCH_WITH_CLI: true  # Workaround for windows "spurious network error".
                                      # Try to remove it on the next MSRV bump.

jobs:
  # Auto-format, clippy and rustc lints do not depend on the operating system
  # and only need to be tested on the latest supported release of each CI run.
  # We don't care about warnings on the minimum supported Rust version, only
  # about building and running correctly.
  lints:
    # Only run on "pull_request" event for external PRs. This is to avoid
    # duplicate builds for PRs created from internal branches.
    if: github.event_name == 'push' || github.event_name == 'schedule' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up stable toolchain
        if: github.event_name != 'schedule'
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt,clippy

      - name: Set up nightly toolchain
        if: github.event_name == 'schedule'
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt,clippy

      - name: Check format
        uses: actions-rust-lang/rustfmt@v1

      - name: Type-check the program
        run: cargo check

      - name: Check clippy lints
        run: cargo clippy -- -D warnings


  # Run the tests on all supported OSes and Rust versions (main CI)
  test-contrib:
    # Only run on "pull_request" event for external PRs. This is to avoid
    # duplicate builds for PRs created from internal branches.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        rust:
          - stable
          - $MINIMAL_RUST

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}

      - name: Run basic tests
        run: cargo test

      - name: Run concurrent tests
        # FIXME: macOS runners are too overloaded for concurrent testing
        if: runner.os != 'macOS'
        run: cargo test --release -- --ignored --test-threads=1


  # Run the tests in Miri for more thorough runtime checks
  #
  # Since Miri is an abstract machine and this crate contains no OS-specific
  # code, testing on one single OS is sufficient. Per Miri documentation, Linux
  # gets the highest-quality support, so that's our obvious pick.
  miri:
    # Only run on "pull_request" event for external PRs. This is to avoid
    # duplicate builds for PRs created from internal branches.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository || github.event_name == 'schedule'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: miri,rust-src
          toolchain: nightly

      - name: Run tests
        run: cargo +nightly miri test --features=miri -- --include-ignored

  # Check compatibility with newer Rust/deps versions (scheduled CI)
  #
  # FIXME: There should be a way to use conditional build matrices without
  #        duplicating the whole job recipe...
  #
  test-scheduled:
    if: github.event_name == 'schedule'

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        rust:
          - beta
          - nightly
          - $MINIMAL_RUST  # Can be broken by deps

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}

      - name: Run basic tests
        run: cargo test

      - name: Run concurrent tests and benchmarks
        # FIXME: macOS runners are too overloaded for concurrent testing
        if: runner.os != 'macOS'
        run: cargo test --release -- --ignored --test-threads=1
